---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[bot] actions"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[bot] javascript"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[bot] ruby"
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: "daily"
      time: "03:27"
      timezone: America/Los_Angeles
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "[bot] docker"
  ## python dir
  - package-ecosystem: docker
    directory: "/python"
    schedule:
      interval: "daily"
      time: "03:12"
      timezone: America/Los_Angeles
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "[bot] docker"
  - package-ecosystem: pip
    directory: "/python"
    schedule:
      interval: "daily"
      time: "03:12"
      timezone: America/Los_Angeles
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "[bot] pip"
  ## python2 dir
  - package-ecosystem: docker
    directory: "/python2"
    schedule:
      interval: "daily"
      time: "03:12"
      timezone: America/Los_Angeles
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "[bot] docker"
  - package-ecosystem: pip
    directory: "/python2"
    schedule:
      interval: "daily"
      time: "03:12"
      timezone: America/Los_Angeles
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "[bot] python"
  - package-ecosystem: pip
    directory: "/python3"
    schedule:
      interval: "daily"
      time: "03:30"
      timezone: America/Los_Angeles
    groups:
      python-deps:
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "[bot] python"
  - package-ecosystem: pip
    directory: "/python4"
    schedule:
      interval: "daily"
      time: "03:30"
      timezone: America/Los_Angeles
    groups:
      python-deps:
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
        - "major"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "[bot] python"
