name: Buildtest

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      # The following properties are now available:
      #  - steps.metadata.outputs.dependency-names
      #  - steps.metadata.outputs.dependency-type
      #  - steps.metadata.outputs.update-type

      - name: Test received vars
        env:
          APP_DIR: ${{ steps.metadata.outputs.directory }}
          DEP_GROUP: ${{ steps.metadata.outputs.dependency-group }}
          WORKING_DIR: ${APP_DIR//-$DEP_GROUP/}
        run: |
          echo ${{ inputs.directory }}
          echo ${{ steps.metadata.outputs.dependency-names }}
          echo ${{ steps.metadata.outputs.dependency-type }}
          echo ${{ steps.metadata.outputs.update-type }}
          echo ${APP_DIR}
          echo ${APP_DIR//-$DEP_GROUP/}
          ls
          echo ${WORKING_DIR}


      - name: More test
        env:
          APP_DIR: ${{ steps.metadata.outputs.directory }}
          DEP_GROUP: ${{ steps.metadata.outputs.dependency-group }}
          WORKING_DIR: ${APP_DIR//-$DEP_GROUP/}
        working-directory: $WORKING_DIR
        run: |
          ls
          ls ${APP_DIR//-$DEP_GROUP/}
          ls $WORKING_DIR
