name: Buildtest

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string

permissions:
  ## https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#automatically-approving-a-pull-request
  pull-requests: write ## For approval and merge
  ## https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enabling-automerge-on-a-pull-request
  contents: write ## For merge

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      # The following properties are now available:
      #  - steps.metadata.outputs.dependency-names
      #  - steps.metadata.outputs.dependency-type
      #  - steps.metadata.outputs.update-type

      - name: Get app dir
        id: app-dir
        env:
          ORIG_OUTPUT_DIR: ${{ steps.metadata.outputs.directory }}
          DEP_GROUP: ${{ steps.metadata.outputs.dependency-group }}
          DEP_NAME: ${{ steps.metadata.outputs.dependency-names }}
        run: >-
          if [[ -n $DEP_GROUP ]]; then
            echo "APP_DIR=${ORIG_OUTPUT_DIR//-$DEP_GROUP/}" >> $GITHUB_OUTPUT
          else
            echo "APP_DIR=${ORIG_OUTPUT_DIR//-$DEP_NAME/}" >> $GITHUB_OUTPUT
          fi

      - name: Set env
        run: >-
          echo "APP_WORK_DIR=${{ github.workspace }}/${{ steps.app-dir.outputs.APP_DIR }}" >> $GITHUB_ENV

      - name: Test received vars
        run: |
          echo "APP_WORK_DIR ${{ env.APP_WORK_DIR }}"
          echo "DEP NAME ${{ steps.metadata.outputs.dependency-names }}"
          echo "DEP TYPE ${{ steps.metadata.outputs.dependency-type }}"
          echo "UPD TYPE ${{ steps.metadata.outputs.update-type }}"
          ls ${{ env.APP_WORK_DIR }}
          pwd
          echo "space: ${{ github.workspace }}"

      - name: More test
        working-directory: ${{ env.APP_WORK_DIR }}
        run: |
          pwd
          ls
          docker build -t local .

  test:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    name: Quick configurable test exit status
    needs:
      - build
    steps:
      - name: exit status
        run: exit 0

  merge:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    name: Enable auto-merge for Dependabot PRs
    needs:
      - test
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
      - name: merge
        run: gh pr merge --auto --squash --delete-branch "$PR_URL" # Use Github CLI to merge automatically the PR


