name: Buildtest

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string

env:
  ALLOWED_APPS: "python,python2,python3,python4,python5,ruby,javascript,docker"

permissions:
#  ## https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#automatically-approving-a-pull-request
  pull-requests: write ## For approval, label, and merge
#  ## https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enabling-automerge-on-a-pull-request
#  contents: write ## For merge

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Detect Directory Changes
        id: changed-files
        uses: tchupp/actions-detect-directory-changes@v1
        with:
          included-paths: ${{ env.ALLOWED_APPS }}

      - name: Set env
        env:
          CHANGED_FILES_APP_NAMES: ${{ join(fromJSON(steps.changed-files.outputs.changed)) }}
        run: >-
          echo "APP_WORK_DIR=${{ github.workspace }}/$CHANGED_FILES_APP_NAMES" >> $GITHUB_ENV


      - name: Test received vars
        run: |
          echo "APP_WORK_DIR ${{ env.APP_WORK_DIR }}"
          ls ${{ env.APP_WORK_DIR }}
          pwd
          echo "space: ${{ github.workspace }}"

      - name: More test
        working-directory: ${{ env.APP_WORK_DIR }}
        run: |
          pwd
          ls
          docker build -t local .

  test:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    name: Quick configurable test exit status
    needs:
      - build
    steps:
      - name: exit status
        run: exit 0

  #label:
  #  if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' && github.ref != 'refs/heads/main' }}
  #  runs-on: ubuntu-latest
  #  name: Test labels
  #  steps:
  #    - name: Add testing label
  #      env:
  #        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #        PR_URL: ${{github.event.pull_request.html_url}}
  #      run: |
  #        gh pr edit "$PR_URL" --add-label "question";

  #    - name: rm and add another testing label
  #      env:
  #        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #        PR_URL: ${{github.event.pull_request.html_url}}
  #      run: |
  #        gh pr edit "$PR_URL" --remove-label "question";
  #        gh pr edit "$PR_URL" --add-label "wontfix";

  merge:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    name: Enable auto-merge for Dependabot PRs
    needs:
      - test
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
    steps:
      - name: Approve a PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr review --approve "$PR_URL"

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.DEPENDABOT_MERGE_APP_ID }}
          private-key: ${{ secrets.DEPENDABOT_MERGE_APP_PRIVATE_KEY }}

      - name: merge
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: gh pr merge --auto --squash --delete-branch "$PR_URL" # Use Github CLI to merge automatically the PR