name: Buildtest

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      # The following properties are now available:
      #  - steps.metadata.outputs.dependency-names
      #  - steps.metadata.outputs.dependency-type
      #  - steps.metadata.outputs.update-type

      - name: Get app dir
        id: app-dir
        env:
          ORIG_OUTPUT_DIR: ${{ steps.metadata.outputs.directory }}
          DEP_GROUP: ${{ steps.metadata.outputs.dependency-group }}
          DEP_NAME: ${{ steps.metadata.outputs.dependency-names }}
        run: >-
          if [[ -n $DEP_GROUP ]]; then
            echo "APP_DIR=${ORIG_OUTPUT_DIR//-$DEP_GROUP/}" >> $GITHUB_OUTPUT
          else
            echo "APP_DIR=${ORIG_OUTPUT_DIR//-$DEP_NAME/}" >> $GITHUB_OUTPUT
          fi

      - name: Set env
        run: >-
          echo "APP_WORK_DIR=${{ github.workspace }}/${{ steps.app-dir.outputs.APP_DIR }}" >> $GITHUB_ENV

      - name: Test received vars
        run: |
          echo "APP_WORK_DIR ${{ env.APP_WORK_DIR }}"
          echo "DEP NAME ${{ steps.metadata.outputs.dependency-names }}"
          echo "DEP TYPE ${{ steps.metadata.outputs.dependency-type }}"
          echo "UPD TYPE ${{ steps.metadata.outputs.update-type }}"
          ls ${{ env.APP_WORK_DIR }}
          pwd
          echo "space: ${{ github.workspace }}"

      - name: More test
        working-directory: ${{ env.APP_WORK_DIR }}
        run: |
          pwd
          ls
          docker build -t local .
