name: Merge

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
#on:
#  workflow_call:
#    inputs:
#      job:
#        required: true
#        type: string

jobs:
  merge:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') && contains(github.event.pull_request.labels.*.name, 'yes') && !contains(github.event.pull_request.labels.*.name, 'no') }}
    steps:
      - name: test
        run: echo "${{ toJSON(github.event.pull_request.labels.*.name) }}";

  justrun:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "${{ toJSON(github.event.pull_request.labels.*.name) }}";
          echo "${{ toJSON(github.event.pull_request.labels) }}";
